// Fortune cookie data: short, family-friendly one-liners.
export const FORTUNES: string[] = [
  'There are only 10 kinds of people: those who understand binary and those who do not.',
  'The best way to accelerate a computer is the one that accelerates it by 9.8 m/s^2.',
  'To iterate is human, to recurse divine.',
  'A computer once beat me at chess, but it was no match for me at kick boxing.',
  'In a world without fences and walls, who needs gates and windows?',
  'There is no place like 127.0.0.1.',
  'The code you write makes a better developer out of you.',
  'Deleted code is debugged code.',
  'If at first you do not succeed, call it version 1.0.',
  'Programming is 10% science, 20% ingenuity and 70% getting the ingenuity to work with the science.',
  'It works on my machine.',
  'A good programmer is someone who always looks both ways before crossing a one-way street.',
  'The sooner you start to code, the longer the program will take.',
  'Real programmers count from 0.',
  'There is no off switch on a tiger, and no undo for rm.',
  'First, solve the problem. Then, write the code.',
  'Before software can be reusable it first has to be usable.',
  'One mans crappy software is another mans full time job.',
  'Copy and paste is a design error.',
  'Measuring programming progress by lines of code is like measuring aircraft building progress by weight.',
  'Nine people cannot make a baby in one month.',
  'The cheapest, fastest and most reliable components are those that are not there.',
  'Weeks of coding can save you hours of planning.',
  'A SQL query goes into a bar, walks up to two tables and asks, can I join you?',
  'Unix is user friendly. It is just selective about who its friends are.',
  'There are two ways of constructing a software design: one way is to make it so simple that there are obviously no deficiencies, and the other way is to make it so complicated that there are no obvious deficiencies.',
  'Any sufficiently advanced bug is indistinguishable from a feature.',
  'The computer was born to solve problems that did not exist before.',
  'Hardware eventually fails. Software eventually works.',
  'Documentation is like sex: when it is good, it is very, very good; and when it is bad, it is better than nothing.',
  'Software is like entropy: it is difficult to grasp, weighs nothing, and obeys the second law of thermodynamics.',
  'An optimist says the glass is half full. A pessimist says it is half empty. An engineer says it is twice as big as it needs to be.',
  'The problem with troubleshooting is that trouble shoots back.',
  'Java is to JavaScript what car is to carpet.',
  'If debugging is the process of removing bugs, then programming must be the process of putting them in.',
  'Always code as if the person who ends up maintaining your code is a violent psychopath who knows where you live.',
  'The floppy disk icon means save, and kids today have no idea why.',
  'Computers are like air conditioners: they stop working when you open Windows.',
  'The Internet: where men are men, women are men, and children are FBI agents.',
  'I would love to change the world, but they will not give me the source code.',
  'Artificial intelligence is no match for natural stupidity.',
  'A clear conscience is usually the sign of a bad memory.',
  'Never put off until tomorrow what you can avoid altogether.',
  'The road to success is always under construction.',
  'I am not lazy, I am on energy saving mode.',
  'Life is short, use semicolons.',
  'I have not failed. I have just found 10,000 ways that will not work.',
  'The early bird gets the worm, but the second mouse gets the cheese.',
  'There are no shortcuts to any place worth going.',
  'An investment in knowledge pays the best interest.',
  'Nothing is impossible, the word itself says I am possible.',
  'The best time to plant a tree was 20 years ago. The second best time is now.',
  'Everything should be made as simple as possible, but not simpler.',
  'Simplicity is the ultimate sophistication.',
  'Do not worry about people stealing your ideas. If your ideas are any good, you will have to ram them down their throats.',
  'The question of whether a computer can think is no more interesting than the question of whether a submarine can swim.',
  'A year spent in artificial intelligence is enough to make one believe in God.',
  'Any sufficiently advanced technology is indistinguishable from magic.',
  'The great thing about standards is that there are so many to choose from.',
  'There are two hard things in computer science: cache invalidation, naming things, and off-by-one errors.',
  'A user interface is like a joke. If you have to explain it, it is not that good.',
  'Walking on water and developing software from a specification are easy if both are frozen.',
  'It is not a bug, it is an undocumented feature.',
  'You are not your code.',
  'Keep it simple, keep it small, keep it yours.',
  'The only way to go fast is to go well.',
  'When in doubt, reboot. When still in doubt, reinstall.',
  'Computers make very fast, very accurate mistakes.',
  'Programs must be written for people to read, and only incidentally for machines to execute.',
  'Perl: the only language that looks the same before and after RSA encryption.',
  'C is quirky, flawed, and an enormous success.',
  'The best thing about a boolean is even if you are wrong, you are only off by a bit.',
  'I do not always test my code, but when I do, I do it in production.',
  'Your password must contain an uppercase letter, a number, a haiku, a gang sign and a hieroglyph.',
  'There is a special place in hell for people who write self-modifying code.',
  'Programmer: a machine that turns coffee into code.',
  'Keyboard not found. Press F1 to continue.',
  'Error 404: witty fortune not found.',
  'I am not a robot, but I play one in the terminal.',
  'Ahmed approved this fortune.',
  'Every exit is an entry somewhere else.',
  'This fortune intentionally left blank.',
]

export const FORTUNES_SHORT: string[] = FORTUNES.filter((f) => f.length <= 60)
