// src/lib/games/mahjong-solitaire.ts
/**
 * Pure Mahjong solitaire logic. No DOM, no React; every function returns a new
 * state and the state is plain JSON (safe for localStorage).
 *
 * Geometry is in half-tile units: a tile at (x, y, z) covers x..x+2, y..y+2 on
 * layer z. A tile is FREE when nothing on a higher layer overlaps it AND at
 * least one of its left/right neighbours (same layer, exactly 2 units away and
 * overlapping vertically) is absent.
 *
 * Deals are generated by reverse play: pairs of free positions are removed from
 * the full layout one after another and given matching tiles, so replaying that
 * removal order is a guaranteed solution. Deterministic for a given seed.
 */
import { type TileCode, fullSet, mulberry32, parseTile, shuffle, tileCode } from './mahjong-tiles'

export type LayoutId = 'turtle' | 'pyramid' | 'fortress'
export interface Pos { x: number; y: number; z: number }
export interface Layout { id: LayoutId; name: string; positions: Pos[] }

export interface SolitaireTile extends Pos {
  /** Index into the layout's positions; stable for the life of the game. */
  id: number
  code: TileCode
  removed: boolean
}
export interface SolitaireState {
  layoutId: LayoutId
  seed: number
  tiles: SolitaireTile[]
  /** Removed pairs in order, most recent last (used by undo). */
  history: [number, number][]
  selected: number | null
}
export type Move = [number, number]

// ---------------------------------------------------------------- layouts

/** cols x rows block of tiles whose top-left tile starts at (x, y) half-units. */
function block(z: number, x: number, y: number, cols: number, rows: number): Pos[] {
  const out: Pos[] = []
  for (let r = 0; r < rows; r++) for (let c = 0; c < cols; c++) out.push({ x: x + 2 * c, y: y + 2 * r, z })
  return out
}

const byDepth = (a: Pos, b: Pos) => a.z - b.z || a.y - b.y || a.x - b.x

function turtlePositions(): Pos[] {
  // [row (tiles), first column (tiles), count]
  const rows: [number, number, number][] = [
    [0, 1, 12], [1, 3, 8], [2, 2, 10], [3, 1, 12],
    [4, 1, 12], [5, 2, 10], [6, 3, 8], [7, 1, 12],
  ]
  const out: Pos[] = []
  for (const [row, col, n] of rows) out.push(...block(0, col * 2, row * 2, n, 1))
  // the "head" and the two "tail" tiles sit half a row down
  out.push({ x: 0, y: 7, z: 0 }, { x: 26, y: 7, z: 0 }, { x: 28, y: 7, z: 0 })
  out.push(...block(1, 8, 2, 6, 6), ...block(2, 10, 4, 4, 4), ...block(3, 12, 6, 2, 2))
  out.push({ x: 13, y: 7, z: 4 })
  return out.sort(byDepth)
}

function pyramidPositions(): Pos[] {
  return [
    ...block(0, 0, 0, 8, 6),
    ...block(1, 2, 2, 6, 4),
    ...block(2, 4, 4, 4, 2),
    ...block(3, 6, 5, 2, 1),
  ].sort(byDepth)
}

function fortressPositions(): Pos[] {
  const out: Pos[] = [...block(0, 0, 0, 10, 4)]
  // four corner towers (2x2), a central keep, and a cap on each tower
  for (const tx of [0, 16]) for (const ty of [0, 4]) out.push(...block(1, tx, ty, 2, 2))
  out.push(...block(1, 6, 2, 4, 2))
  for (const [tx, ty] of [[1, 1], [17, 1], [1, 5], [17, 5]]) out.push({ x: tx, y: ty, z: 2 })
  return out.sort(byDepth)
}

export const LAYOUTS: Record<LayoutId, Layout> = {
  turtle: { id: 'turtle', name: 'Turtle', positions: turtlePositions() },
  pyramid: { id: 'pyramid', name: 'Pyramid', positions: pyramidPositions() },
  fortress: { id: 'fortress', name: 'Fortress', positions: fortressPositions() },
}
export const LAYOUT_IDS: LayoutId[] = ['turtle', 'pyramid', 'fortress']

export function isLayoutId(v: unknown): v is LayoutId {
  return typeof v === 'string' && Object.prototype.hasOwnProperty.call(LAYOUTS, v)
}

// ---------------------------------------------------------------- matching

/** Identical codes match; any flower matches any flower, any season any season. */
export function tilesMatch(a: TileCode, b: TileCode): boolean {
  const ka = parseTile(a)
  const kb = parseTile(b)
  if (!ka || !kb) return false
  if (ka.suit === kb.suit && (ka.rank === kb.rank || ka.suit === 'flowers' || ka.suit === 'seasons')) return true
  return false
}

/** Key such that two tiles match iff their keys are equal. */
function matchKey(code: TileCode): string {
  const k = parseTile(code)
  if (k && (k.suit === 'flowers' || k.suit === 'seasons')) return k.suit
  return code
}

// ---------------------------------------------------------------- free rule

/** Is tile `i` free, considering only tiles for which alive[j] is true? */
function freeAt(ps: readonly Pos[], alive: readonly boolean[], i: number): boolean {
  const p = ps[i]
  let left = false
  let right = false
  for (let j = 0; j < ps.length; j++) {
    if (j === i || !alive[j]) continue
    const q = ps[j]
    const dy = Math.abs(q.y - p.y)
    if (dy >= 2) continue
    if (q.z > p.z) {
      if (Math.abs(q.x - p.x) < 2) return false
    } else if (q.z === p.z) {
      if (q.x === p.x - 2) left = true
      else if (q.x === p.x + 2) right = true
    }
  }
  return !(left && right)
}

function aliveOf(state: SolitaireState): boolean[] {
  return state.tiles.map((t) => !t.removed)
}

export function isFree(state: SolitaireState, id: number): boolean {
  const t = state.tiles[id]
  if (!t || t.removed) return false
  return freeAt(state.tiles, aliveOf(state), id)
}

export function freeTiles(state: SolitaireState): SolitaireTile[] {
  const alive = aliveOf(state)
  return state.tiles.filter((t) => alive[t.id] && freeAt(state.tiles, alive, t.id))
}

// ---------------------------------------------------------------- deal generation

const MAX_ATTEMPTS = 500

/** Matching pairs of codes from a multiset; null when it cannot be fully paired. */
function pairUp(codes: readonly TileCode[], rng: () => number): [TileCode, TileCode][] | null {
  const groups = new Map<string, TileCode[]>()
  for (const c of codes) {
    const key = matchKey(c)
    const g = groups.get(key)
    if (g) g.push(c)
    else groups.set(key, [c])
  }
  const pairs: [TileCode, TileCode][] = []
  for (const g of groups.values()) {
    if (g.length % 2) return null
    const s = shuffle(g, rng)
    for (let i = 0; i < s.length; i += 2) pairs.push([s[i], s[i + 1]])
  }
  return pairs
}

/**
 * Reverse play over `ps`: repeatedly remove two random free positions and give
 * them a pair from `pairs`. Returns codes by position plus the removal order
 * (a valid forward solution), or null if it dead-ended.
 */
function reversePlay(
  ps: readonly Pos[],
  pairs: readonly [TileCode, TileCode][],
  rng: () => number,
): { codes: TileCode[]; solution: Move[] } | null {
  const n = ps.length
  const order = shuffle(pairs, rng)
  const alive = new Array<boolean>(n).fill(true)
  const codes = new Array<TileCode>(n)
  const solution: Move[] = []
  for (let step = 0; step < n / 2; step++) {
    const free: number[] = []
    for (let i = 0; i < n; i++) if (alive[i] && freeAt(ps, alive, i)) free.push(i)
    if (free.length < 2) return null
    const a = free.splice(Math.floor(rng() * free.length), 1)[0]
    const b = free[Math.floor(rng() * free.length)]
    let [ca, cb] = order[step]
    if (rng() < 0.5) [ca, cb] = [cb, ca]
    codes[a] = ca
    codes[b] = cb
    alive[a] = alive[b] = false
    solution.push([a, b])
  }
  return { codes, solution }
}

/** Tile codes by layout position plus a known solution. Deterministic per seed. */
export function generateDeal(layoutId: LayoutId, seed: number): { codes: TileCode[]; solution: Move[] } {
  const ps = LAYOUTS[layoutId].positions
  const rng = mulberry32(seed)
  const pool = pairUp(fullSet(true), rng)!
  for (let attempt = 0; attempt < MAX_ATTEMPTS; attempt++) {
    const picked = shuffle(pool, rng).slice(0, ps.length / 2)
    const deal = reversePlay(ps, picked, rng)
    if (deal) return deal
  }
  throw new Error(`mahjong-solitaire: could not generate a deal for ${layoutId}`)
}

export function newGame(layoutId: LayoutId, seed: number): SolitaireState {
  const { positions } = LAYOUTS[layoutId]
  const { codes } = generateDeal(layoutId, seed)
  return {
    layoutId,
    seed,
    tiles: positions.map((p, id) => ({ id, code: codes[id], x: p.x, y: p.y, z: p.z, removed: false })),
    history: [],
    selected: null,
  }
}

// ---------------------------------------------------------------- moves

export function tilesLeft(state: SolitaireState): number {
  let n = 0
  for (const t of state.tiles) if (!t.removed) n++
  return n
}
export const isWon = (state: SolitaireState): boolean => state.tiles.length > 0 && tilesLeft(state) === 0

export function canMatch(state: SolitaireState, a: number, b: number): boolean {
  if (a === b) return false
  const ta = state.tiles[a]
  const tb = state.tiles[b]
  if (!ta || !tb || ta.removed || tb.removed) return false
  if (!tilesMatch(ta.code, tb.code)) return false
  const alive = aliveOf(state)
  return freeAt(state.tiles, alive, a) && freeAt(state.tiles, alive, b)
}

/** Remove a matching free pair. Returns the same state object if the move is illegal. */
export function removePair(state: SolitaireState, a: number, b: number): SolitaireState {
  if (!canMatch(state, a, b)) return state
  return {
    ...state,
    tiles: state.tiles.map((t) => (t.id === a || t.id === b ? { ...t, removed: true } : t)),
    history: [...state.history, [a, b]],
    selected: null,
  }
}

/** Restore the most recently removed pair (no-op when history is empty). */
export function undo(state: SolitaireState): SolitaireState {
  const last = state.history[state.history.length - 1]
  if (!last) return state
  return {
    ...state,
    tiles: state.tiles.map((t) => (t.id === last[0] || t.id === last[1] ? { ...t, removed: false } : t)),
    history: state.history.slice(0, -1),
    selected: null,
  }
}

/** Every matchable pair of free tiles, each pair once with a < b. */
export function availableMoves(state: SolitaireState): Move[] {
  const groups = new Map<string, number[]>()
  for (const t of freeTiles(state)) {
    const key = matchKey(t.code)
    const g = groups.get(key)
    if (g) g.push(t.id)
    else groups.set(key, [t.id])
  }
  const moves: Move[] = []
  for (const g of groups.values()) {
    for (let i = 0; i < g.length; i++) for (let j = i + 1; j < g.length; j++) moves.push([g[i], g[j]])
  }
  return moves
}

/**
 * Suggest a move. One-ply lookahead: prefer the pair that leaves the most
 * follow-up moves (a win beats everything), so hints avoid obvious dead ends.
 */
export function hint(state: SolitaireState): Move | null {
  const moves = availableMoves(state)
  let best: Move | null = null
  let bestScore = -1
  for (const m of moves) {
    const next = removePair(state, m[0], m[1])
    const score = tilesLeft(next) === 0 ? Infinity : availableMoves(next).length
    if (score > bestScore) {
      bestScore = score
      best = m
    }
  }
  return best
}

export const isStuck = (state: SolitaireState): boolean =>
  tilesLeft(state) > 0 && availableMoves(state).length === 0

/**
 * Click handling: select a free tile, deselect it, or remove the pair when the
 * clicked tile matches the selection. Anything else leaves state unchanged.
 */
export function selectTile(state: SolitaireState, id: number): SolitaireState {
  if (!isFree(state, id)) return state
  const sel = state.selected
  if (sel === null || sel === undefined) return { ...state, selected: id }
  if (sel === id) return { ...state, selected: null }
  if (canMatch(state, sel, id)) return removePair(state, sel, id)
  return { ...state, selected: id }
}

/**
 * Reshuffle the remaining tiles among the remaining positions, preferring an
 * arrangement that is solvable from here (reverse play on the remaining
 * positions). Falls back to a plain shuffle. Clears undo history and selection:
 * past pairs no longer line up with the reshuffled board.
 */
export function shuffleRemaining(state: SolitaireState, rng: () => number): SolitaireState {
  const rest = state.tiles.filter((t) => !t.removed)
  if (rest.length < 2) return { ...state, history: [], selected: null }
  const ps: Pos[] = rest.map((t) => ({ x: t.x, y: t.y, z: t.z }))
  const pairs = pairUp(
    rest.map((t) => t.code),
    rng,
  )
  let codes: TileCode[] | null = null
  if (pairs) {
    for (let attempt = 0; attempt < MAX_ATTEMPTS && !codes; attempt++) codes = reversePlay(ps, pairs, rng)?.codes ?? null
  }
  const assigned = codes ?? shuffle(rest.map((t) => t.code), rng)
  const byId = new Map(rest.map((t, i) => [t.id, assigned[i]]))
  return {
    ...state,
    tiles: state.tiles.map((t) => (t.removed ? t : { ...t, code: byId.get(t.id)! })),
    history: [],
    selected: null,
  }
}

/** Tiles sorted back-to-front (z, then y, then x) for painting. Removed tiles are skipped by default. */
export function renderOrder(state: SolitaireState, includeRemoved = false): SolitaireTile[] {
  return state.tiles.filter((t) => includeRemoved || !t.removed).sort(byDepth)
}

// ---------------------------------------------------------------- persistence

const isInt = (v: unknown): v is number => typeof v === 'number' && Number.isSafeInteger(v)

/** Strictly validate untrusted (localStorage) data. Returns a fresh state or null. */
export function validateSave(raw: unknown): SolitaireState | null {
  if (typeof raw !== 'object' || raw === null || Array.isArray(raw)) return null
  const r = raw as Record<string, unknown>
  if (!isLayoutId(r.layoutId) || !isInt(r.seed)) return null
  const layout = LAYOUTS[r.layoutId]
  const n = layout.positions.length
  if (!Array.isArray(r.tiles) || r.tiles.length !== n) return null

  const tiles: SolitaireTile[] = []
  for (let i = 0; i < n; i++) {
    const t = r.tiles[i]
    if (typeof t !== 'object' || t === null || Array.isArray(t)) return null
    const o = t as Record<string, unknown>
    const p = layout.positions[i]
    if (o.id !== i || o.x !== p.x || o.y !== p.y || o.z !== p.z) return null
    if (typeof o.removed !== 'boolean' || typeof o.code !== 'string') return null
    const kind = parseTile(o.code)
    if (!kind || tileCode(kind) !== o.code) return null
    tiles.push({ id: i, code: o.code, x: p.x, y: p.y, z: p.z, removed: o.removed })
  }

  // Remaining tiles must be fully pairable, or the game could never be won.
  const counts = new Map<string, number>()
  let removedCount = 0
  for (const t of tiles) {
    if (t.removed) removedCount++
    else counts.set(matchKey(t.code), (counts.get(matchKey(t.code)) ?? 0) + 1)
  }
  if (removedCount % 2) return null
  for (const c of counts.values()) if (c % 2) return null

  if (!Array.isArray(r.history) || r.history.length > n / 2) return null
  const history: [number, number][] = []
  const seen = new Set<number>()
  for (const h of r.history) {
    if (!Array.isArray(h) || h.length !== 2) return null
    const [a, b] = h as unknown[]
    if (!isInt(a) || !isInt(b) || a === b || !tiles[a] || !tiles[b]) return null
    if (!tiles[a].removed || !tiles[b].removed || seen.has(a) || seen.has(b)) return null
    if (!tilesMatch(tiles[a].code, tiles[b].code)) return null
    seen.add(a)
    seen.add(b)
    history.push([a, b])
  }

  let selected: number | null = null
  if (r.selected !== undefined && r.selected !== null) {
    if (!isInt(r.selected) || !tiles[r.selected] || tiles[r.selected].removed) return null
    selected = r.selected
  }
  return { layoutId: r.layoutId, seed: r.seed, tiles, history, selected }
}
