// Generated by scripts/draw-desk-shelf-items.mjs. Do not edit: rerun
//   node scripts/draw-desk-shelf-items.mjs
//
// The shelf's items as drawn for the desk close-up, in render order (later
// stands in front). Boxes are in close-up stage px (the shelf sits at negative
// y, above the stage); frames are /room/desk-shelf-<id>-1..3.png (rest, then
// the two-step highlight); `hit` is the rest pixels as an SVG path local to
// the box, for CSS clip-path.

export const DESK_SHELF_SPRITES = [
  { id: 'catan', kind: 'catan', x: 58, y: -104, w: 214, h: 136,
    hit: 'M6 4h184v2h-184zM192 4h2v2h-2zM4 6h196v2h-196zM4 8h198v38h-198zM6 46h196v2h-196zM12 48h196v2h-196zM12 50h198v38h-198zM8 88h190v2h-190zM200 88h8v2h-8zM6 90h196v2h-196zM6 92h198v38h-198zM8 130h184v2h-184zM194 130h8v2h-8z' },
  { id: 'moby-dick', kind: 'book', x: 258, y: -130, w: 36, h: 164,
    hit: 'M6 4h24v2h-24zM4 6h28v152h-28zM6 158h24v2h-24z' },
  { id: 'nineteen-eighty-four', kind: 'book', x: 284, y: -154, w: 38, h: 188,
    hit: 'M6 4h26v2h-26zM4 6h30v176h-30zM6 182h26v2h-26z' },
  { id: 'odyssey', kind: 'book', x: 312, y: -142, w: 52, h: 176,
    hit: 'M6 4h32v2h-32zM40 4h2v2h-2zM4 6h42v2h-42zM4 8h44v162h-44zM6 170h32v2h-32zM40 170h6v2h-6z' },
  { id: 'vhs', kind: 'vhs', x: 348, y: -32, w: 114, h: 66,
    hit: 'M14 4h84v2h-84zM12 6h92v2h-92zM12 8h94v14h-94zM6 22h98v2h-98zM4 24h102v2h-102zM4 26h104v16h-104zM6 42h100v2h-100zM8 44h100v2h-100zM8 46h102v14h-102zM10 60h92v2h-92zM104 60h4v2h-4z' },
  { id: 'chess', kind: 'game', x: 450, y: -64, w: 102, h: 98,
    hit: 'M8 4h80v2h-80zM6 6h88v2h-88zM6 8h90v62h-90zM4 70h92v4h-92zM6 74h90v14h-90zM4 88h92v2h-92zM4 90h94v2h-94zM6 92h90v2h-90z' },
  { id: 'mahjong', kind: 'game', x: 544, y: -36, w: 94, h: 68,
    hit: 'M12 4h22v2h-22zM36 4h22v2h-22zM60 4h22v2h-22zM10 6h74v28h-74zM8 34h80v2h-80zM6 36h84v12h-84zM6 48h82v2h-82zM4 50h84v12h-84zM6 62h80v2h-80z' },
  { id: 'solitaire', kind: 'game', x: 630, y: -40, w: 54, h: 74,
    hit: 'M6 4h36v2h-36zM4 6h44v2h-44zM4 8h46v60h-46zM6 68h36v2h-36zM44 68h4v2h-4z' },
  { id: 'blackjack', kind: 'game', x: 672, y: -22, w: 56, h: 56,
    hit: 'M8 4h26v2h-26zM6 6h30v2h-30zM6 8h44v2h-44zM6 10h46v22h-46zM4 32h48v18h-48zM6 50h18v2h-18zM32 50h18v2h-18z' },
  { id: 'minesweeper', kind: 'game', x: 714, y: -40, w: 82, h: 74,
    hit: 'M24 4h52v2h-52zM22 6h56v6h-56zM6 12h2v2h-2zM10 12h68v2h-68zM4 14h74v46h-74zM4 60h72v2h-72zM4 62h60v6h-60zM6 68h2v2h-2zM10 68h52v2h-52z' },
  { id: 'snake', kind: 'game', x: 782, y: -44, w: 46, h: 78,
    hit: 'M12 4h28v2h-28zM6 6h36v2h-36zM4 8h38v64h-38zM6 72h4v2h-4zM12 72h28v2h-28z' },
  { id: 'breakout', kind: 'game', x: 814, y: -40, w: 58, h: 74,
    hit: 'M12 4h40v2h-40zM6 6h48v2h-48zM4 8h50v60h-50zM6 68h4v2h-4zM12 68h40v2h-40z' },
  { id: 'pong', kind: 'game', x: 856, y: -40, w: 58, h: 74,
    hit: 'M12 4h40v2h-40zM6 6h48v2h-48zM4 8h50v60h-50zM6 68h4v2h-4zM12 68h40v2h-40z' },
] as const
