export interface Track {
  id: string
  title: string
  artist?: string
  src: string
  cover?: string
}

export const PLAYLIST: Track[] = [
  {
    id: 'cant-look-in-my-eyes',
    title: "Can't Look In My Eyes",
    src: '/audio/cant-look-in-my-eyes.mp3',
    cover: '/audio/covers/cant-look-in-my-eyes.jpg',
  },
  {
    id: 'remember-summer-days',
    title: 'Remember Summer Days',
    src: '/audio/remember-summer-days.mp3',
    cover: '/audio/covers/summer-days.jpg',
  },
  {
    id: 'sky-restaurant',
    title: 'Sky Restaurant',
    src: '/audio/sky-restaurant.mp3',
    cover: '/audio/covers/sky-restaurant.jpg',
  },
  {
    id: 'teresa-no-tameiki',
    title: 'Teresa no Tameiki',
    artist: 'Yasushi Miyagawa',
    src: '/audio/teresa-no-tameiki.mp3',
    cover: '/audio/covers/teresa-no-tameiki.jpg',
  },
  {
    id: 'fall-in-love',
    title: '(You And Me Still Keep On) Fall In Love',
    artist: 'Mai Yamane',
    src: '/audio/fall-in-love.mp3',
    cover: '/audio/covers/fall-in-love.jpg',
  },
  {
    id: 'hako-is-alive',
    title: 'Hako Is Alive and She Is 59',
    src: '/audio/hako-is-alive.mp3',
    cover: '/audio/covers/hako-is-alive.jpg',
  },
  {
    id: 'always',
    title: 'Always',
    artist: 'Daniel Caesar',
    src: '/audio/always.mp3',
    cover: '/audio/covers/always.jpg',
  },
  {
    id: 'sukoshidake-mawarimichi',
    title: 'Sukoshidake Mawarimichi',
    artist: 'Hi-Fi Set',
    src: '/audio/sukoshidake-mawarimichi.mp3',
    cover: '/audio/covers/sukoshidake-mawarimichi.jpg',
  },
  {
    id: 'morphine-slowed',
    title: 'Morphine - Slowed',
    artist: 'baby.murcielaga, 1aevne',
    src: '/audio/morphine-slowed.mp3',
    cover: '/audio/covers/morphine-slowed.jpg',
  },
  {
    id: 'pyramids',
    title: 'Pyramids',
    artist: 'Frank Ocean',
    src: '/audio/pyramids.mp3',
    cover: '/audio/covers/pyramids.jpg',
  },
  {
    id: 'where-were-you-when-i-needed-you-the-most',
    title: 'Where Were You When I Needed You the Most',
    artist: 'baby.murcielaga',
    src: '/audio/where-were-you-when-i-needed-you-the-most.mp3',
    cover: '/audio/covers/where-were-you-when-i-needed-you-the-most.jpg',
  },
  {
    id: 'headlines',
    title: 'Headlines',
    artist: 'Drake',
    src: '/audio/headlines.mp3',
    cover: '/audio/covers/headlines.jpg',
  },
  {
    id: 'swim-good',
    title: 'Swim Good',
    artist: 'Frank Ocean',
    src: '/audio/swim-good.mp3',
    cover: '/audio/covers/swim-good.jpg',
  },
  {
    id: 'slow-jamz',
    title: 'Slow Jamz',
    artist: 'Twista, Kanye West, Jamie Foxx',
    src: '/audio/slow-jamz.mp3',
    cover: '/audio/covers/slow-jamz.jpg',
  },
  {
    id: 'year-of-the-cat',
    title: 'Year of the Cat',
    artist: 'Al Stewart',
    src: '/audio/year-of-the-cat.mp3',
    cover: '/audio/covers/year-of-the-cat.jpg',
  },
  {
    id: 'havalie-haram',
    title: 'Havalie Haram',
    artist: 'Hossein Taheri',
    src: '/audio/havalie-haram.mp3',
    cover: '/audio/covers/havalie-haram.jpg',
  },
  {
    id: 'manam-bayad-beram',
    title: 'Manam Bayad Beram',
    artist: 'Hossein Taheri',
    src: '/audio/manam-bayad-beram.mp3',
    cover: '/audio/covers/manam-bayad-beram.jpg',
  },
  {
    id: 'shut-up-my-moms-calling',
    title: 'Shut up My Moms Calling',
    artist: 'Hotel Ugly',
    src: '/audio/shut-up-my-moms-calling.mp3',
    cover: '/audio/covers/shut-up-my-moms-calling.jpg',
  },
  {
    id: 'erin-go-bragh',
    title: 'Erin Go Bragh',
    artist: 'Jimmy & Scots Folk Band',
    src: '/audio/erin-go-bragh.mp3',
    cover: '/audio/covers/erin-go-bragh.jpg',
  },
  {
    id: 'welcome-to-heartbreak',
    title: 'Welcome To Heartbreak',
    artist: 'Kanye West, Kid Cudi',
    src: '/audio/welcome-to-heartbreak.mp3',
    cover: '/audio/covers/welcome-to-heartbreak.jpg',
  },
  {
    id: 'day-n-nite-nightmare',
    title: "Day 'N' Nite (Nightmare)",
    artist: 'Kid Cudi',
    src: '/audio/day-n-nite-nightmare.mp3',
    cover: '/audio/covers/day-n-nite-nightmare.jpg',
  },
  {
    id: 'zivjela-bosna',
    title: 'Živjela Bosna',
    artist: 'Mahir Bureković',
    src: '/audio/zivjela-bosna.mp3',
    cover: '/audio/covers/zivjela-bosna.jpg',
  },
  {
    id: 'gisoo',
    title: 'Gisoo',
    artist: 'Mahmoud Karimi',
    src: '/audio/gisoo.mp3',
    cover: '/audio/covers/gisoo.jpg',
  },
  {
    id: 'ghadam-ghadam',
    title: 'Ghadam Ghadam',
    artist: 'Majid Bani Fatemeh',
    src: '/audio/ghadam-ghadam.mp3',
    cover: '/audio/covers/ghadam-ghadam.jpg',
  },
  {
    id: 'cosmic-gloom',
    title: 'Cosmic Gloom',
    artist: 'Quelle Rox',
    src: '/audio/cosmic-gloom.mp3',
    cover: '/audio/covers/cosmic-gloom.jpg',
  },
  {
    id: 'kiss-from-a-rose',
    title: 'Kiss from a Rose',
    artist: 'Seal',
    src: '/audio/kiss-from-a-rose.mp3',
    cover: '/audio/covers/kiss-from-a-rose.jpg',
  },
  {
    id: 'some',
    title: 'Some',
    artist: 'Steve Lacy',
    src: '/audio/some.mp3',
    cover: '/audio/covers/some.jpg',
  },
]
