// Generated by scripts/extract-shelf.mjs from the art drawn by
// scripts/draw-shelf-games.mjs. Do not edit: rerun
//   node scripts/draw-shelf-games.mjs && node scripts/extract-shelf.mjs && npm run lighting
//
// Each desk game's sprite box on the stage, in render order (an object later in
// the list stands in front of the ones it overlaps), and `hit`, its pixel
// mask as an SVG path local to that box for CSS clip-path.

export const SHELF_GAME_SPRITES = [
  { app: 'chess', x: 286, y: 171, w: 59, h: 67,
    hit: 'M42 0h3v1h-3zM35 1h11v1h-11zM28 2h19v1h-19zM20 3h28v1h-28zM13 4h35v1h-35zM5 5h43v1h-43zM4 6h44v1h-44zM3 7h45v1h-45zM2 8h46v3h-46zM2 11h47v7h-47zM3 18h46v3h-46zM3 21h47v7h-47zM4 28h46v2h-46zM4 30h47v7h-47zM4 37h48v1h-48zM5 38h48v1h-48zM5 39h49v1h-49zM5 40h50v4h-50zM5 44h49v1h-49zM5 45h48v1h-48zM5 46h49v1h-49zM6 47h48v1h-48zM6 48h49v1h-49zM6 49h50v3h-50zM7 52h49v1h-49zM8 53h48v1h-48zM9 54h48v1h-48zM8 55h49v3h-49zM8 58h48v1h-48zM9 59h21v1h-21zM35 59h11v1h-11zM48 59h7v1h-7zM10 60h20v1h-20zM36 60h9v1h-9zM49 60h5v1h-5zM11 61h18v1h-18zM37 61h7v1h-7zM50 61h3v1h-3zM12 62h5v1h-5zM18 62h10v1h-10zM38 62h5v1h-5zM19 63h8v1h-8zM39 63h3v1h-3zM20 64h6v1h-6z' },
  { app: 'mahjong', x: 335, y: 197, w: 58, h: 37,
    hit: 'M41 0h6v1h-6zM34 1h17v1h-17zM26 2h27v1h-27zM19 3h35v1h-35zM11 4h44v1h-44zM5 5h51v1h-51zM4 6h52v1h-52zM3 7h53v1h-53zM2 8h54v11h-54zM2 19h53v1h-53zM2 20h52v1h-52zM2 21h51v1h-51zM3 22h47v1h-47zM3 23h42v7h-42zM3 30h41v1h-41zM4 31h39v1h-39zM5 32h37v1h-37zM6 33h35v1h-35zM7 34h10v1h-10zM18 34h9v1h-9zM31 34h3v1h-3z' },
  { app: 'solitaire', x: 380, y: 181, w: 37, h: 41,
    hit: 'M21 0h3v1h-3zM14 1h14v1h-14zM6 2h25v1h-25zM5 3h27v1h-27zM4 4h29v1h-29zM3 5h31v1h-31zM2 6h33v28h-33zM3 34h31v1h-31zM4 35h29v1h-29zM5 36h27v1h-27zM8 37h19v1h-19zM12 38h7v1h-7z' },
  { app: 'blackjack', x: 391, y: 196, w: 56, h: 29,
    hit: 'M15 0h2v1h-2zM7 1h11v1h-11zM23 1h4v1h-4zM5 2h23v1h-23zM32 2h5v1h-5zM4 3h25v1h-25zM30 3h9v1h-9zM43 3h5v1h-5zM3 4h37v1h-37zM41 4h9v1h-9zM2 5h49v1h-49zM2 6h50v1h-50zM2 7h51v1h-51zM2 8h52v2h-52zM3 10h51v4h-51zM4 14h50v4h-50zM5 18h49v1h-49zM5 19h48v1h-48zM5 20h47v1h-47zM5 21h46v1h-46zM6 22h37v2h-37zM7 24h35v1h-35zM8 25h33v1h-33zM9 26h5v1h-5zM18 26h6v1h-6zM29 26h11v1h-11z' },
  { app: 'minesweeper', x: 435, y: 165, w: 46, h: 43,
    hit: 'M24 0h7v1h-7zM16 1h20v1h-20zM9 2h28v1h-28zM5 3h33v1h-33zM4 4h35v1h-35zM3 5h36v1h-36zM2 6h37v2h-37zM2 8h38v2h-38zM3 10h37v4h-37zM3 14h38v5h-38zM3 19h39v1h-39zM4 20h38v4h-38zM4 24h39v5h-39zM4 29h40v2h-40zM5 31h39v3h-39zM5 34h38v1h-38zM5 35h37v1h-37zM6 36h35v1h-35zM7 37h31v1h-31zM8 38h2v1h-2zM13 38h18v1h-18zM14 39h10v1h-10zM15 40h1v1h-1z' },
  { app: 'snake', x: 463, y: 177, w: 27, h: 41,
    hit: 'M13 0h7v1h-7zM6 1h16v1h-16zM5 2h18v1h-18zM4 3h20v1h-20zM3 4h22v1h-22zM2 5h23v29h-23zM2 34h22v1h-22zM3 35h20v1h-20zM4 36h18v1h-18zM5 37h13v1h-13zM8 38h3v1h-3z' },
  { app: 'breakout', x: 484, y: 163, w: 38, h: 40,
    hit: 'M23 0h3v1h-3zM16 1h14v1h-14zM9 2h24v1h-24zM5 3h29v1h-29zM4 4h31v1h-31zM3 5h33v1h-33zM2 6h34v27h-34zM3 33h32v1h-32zM4 34h30v1h-30zM5 35h28v1h-28zM7 36h18v1h-18zM11 37h7v1h-7z' },
  { app: 'pong', x: 501, y: 170, w: 38, h: 40,
    hit: 'M24 0h2v1h-2zM16 1h14v1h-14zM9 2h24v1h-24zM5 3h29v1h-29zM4 4h31v1h-31zM3 5h33v1h-33zM2 6h34v27h-34zM3 33h32v1h-32zM4 34h30v1h-30zM5 35h28v1h-28zM7 36h19v1h-19zM11 37h7v1h-7z' },
] as const
